spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exercise
    username: root
    password: password
  application: 
    name: donation-camp-service  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}         
  
server:
  port: 6770

